#!/bin/bash
# ============================================================
# Run THIS ONCE on the machine — it makes the specific sudo
# commands password-less so the dashboard can call them.
# Usage:  bash infrastructure/scripts/setup_sudo.sh
# ============================================================

set -e
USER_NAME="${SUDO_USER:-$(whoami)}"

echo "[*] Setting up passwordless sudo for IoT IDS commands..."
echo "    User: $USER_NAME"

SUDOERS_FILE="/etc/sudoers.d/iot-ids"

sudo tee "$SUDOERS_FILE" > /dev/null <<EOF
# IoT IDS — passwordless sudo for pipeline commands
# Generated by setup_sudo.sh — safe to delete after uninstall

# Kernel tuning
$USER_NAME ALL=(ALL) NOPASSWD: /sbin/sysctl -w net.core.rmem_max=*
$USER_NAME ALL=(ALL) NOPASSWD: /sbin/sysctl -w net.core.netdev_max_backlog=*

# PostgreSQL
$USER_NAME ALL=(ALL) NOPASSWD: /bin/systemctl start postgresql
$USER_NAME ALL=(ALL) NOPASSWD: /bin/systemctl stop postgresql
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/systemctl start postgresql
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop postgresql
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/psql *
$USER_NAME ALL=(ALL) NOPASSWD: /bin/su - postgres *
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/sudo -u postgres *

# Zeek
$USER_NAME ALL=(ALL) NOPASSWD: /opt/zeek/bin/zeek *
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/zeek *
$USER_NAME ALL=(ALL) NOPASSWD: /usr/local/bin/zeek *
$USER_NAME ALL=(ALL) NOPASSWD: /bin/pkill -f zeek*
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/pkill -f zeek*

# Suricata
$USER_NAME ALL=(ALL) NOPASSWD: /bin/systemctl start suricata
$USER_NAME ALL=(ALL) NOPASSWD: /bin/systemctl stop suricata
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/systemctl start suricata
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop suricata
$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/suricata *

# Firewall (UFW + iptables) — used by SOAR playbooks
$USER_NAME ALL=(ALL) NOPASSWD: /usr/sbin/ufw *
$USER_NAME ALL=(ALL) NOPASSWD: /sbin/ufw *
$USER_NAME ALL=(ALL) NOPASSWD: /sbin/iptables *
$USER_NAME ALL=(ALL) NOPASSWD: /usr/sbin/iptables *

# Reset script
$USER_NAME ALL=(ALL) NOPASSWD: /bin/bash */infrastructure/scripts/reset_firewall.sh
EOF

# Validate the sudoers file — visudo -c will catch syntax errors
if sudo visudo -c -f "$SUDOERS_FILE" 2>/dev/null; then
    echo "    [✔] Sudoers file valid: $SUDOERS_FILE"
else
    echo "    [!] Sudoers syntax error — removing file to be safe"
    sudo rm -f "$SUDOERS_FILE"
    exit 1
fi

echo ""
echo "============================================================"
echo "  [✔] Passwordless sudo configured for: $USER_NAME"
echo "  Now the dashboard Start Pipeline button works fully."
echo "  To undo: sudo rm $SUDOERS_FILE"
echo "============================================================"
